// Built-in nutrition database — approximate values per 100g, for estimation only.
// Sources: general USDA-style reference values. Always verify against packaging
// or an official database for medical/diet-critical use.
const FOOD_DB = {
  "chicken breast, cooked": { cal: 165, protein: 31, carbs: 0, fat: 3.6 },
  "chicken thigh, cooked": { cal: 209, protein: 26, carbs: 0, fat: 10.9 },
  "ground beef 90/10, cooked": { cal: 217, protein: 26, carbs: 0, fat: 12 },
  "ground turkey, cooked": { cal: 176, protein: 27, carbs: 0, fat: 8 },
  "pork tenderloin, cooked": { cal: 143, protein: 26, carbs: 0, fat: 3.5 },
  "salmon, cooked": { cal: 206, protein: 22, carbs: 0, fat: 13 },
  "tilapia, cooked": { cal: 128, protein: 26, carbs: 0, fat: 2.7 },
  "cod, cooked": { cal: 105, protein: 23, carbs: 0, fat: 0.9 },
  "tuna, canned in water": { cal: 116, protein: 26, carbs: 0, fat: 0.8 },
  "shrimp, cooked": { cal: 99, protein: 24, carbs: 0.2, fat: 0.3 },
  "egg, whole": { cal: 155, protein: 13, carbs: 1.1, fat: 11 },
  "egg white": { cal: 52, protein: 11, carbs: 0.7, fat: 0.2 },
  "tofu, firm": { cal: 144, protein: 17, carbs: 3, fat: 8 },
  "black beans, cooked": { cal: 132, protein: 8.9, carbs: 23.7, fat: 0.5 },
  "chickpeas, cooked": { cal: 164, protein: 8.9, carbs: 27.4, fat: 2.6 },
  "lentils, cooked": { cal: 116, protein: 9, carbs: 20, fat: 0.4 },
  "white rice, cooked": { cal: 130, protein: 2.7, carbs: 28, fat: 0.3 },
  "brown rice, cooked": { cal: 123, protein: 2.7, carbs: 25.6, fat: 1 },
  "quinoa, cooked": { cal: 120, protein: 4.4, carbs: 21.3, fat: 1.9 },
  "sweet potato, baked": { cal: 90, protein: 2, carbs: 20.7, fat: 0.2 },
  "potato, baked": { cal: 93, protein: 2.5, carbs: 21.2, fat: 0.1 },
  "oats, dry": { cal: 389, protein: 16.9, carbs: 66.3, fat: 6.9 },
  "whole wheat bread": { cal: 247, protein: 13, carbs: 41, fat: 3.4 },
  "broccoli, cooked": { cal: 35, protein: 2.4, carbs: 7.2, fat: 0.4 },
  "spinach, raw": { cal: 23, protein: 2.9, carbs: 3.6, fat: 0.4 },
  "kale, raw": { cal: 49, protein: 4.3, carbs: 8.8, fat: 0.9 },
  "bell pepper": { cal: 31, protein: 1, carbs: 6, fat: 0.3 },
  "onion": { cal: 40, protein: 1.1, carbs: 9.3, fat: 0.1 },
  "garlic": { cal: 149, protein: 6.4, carbs: 33, fat: 0.5 },
  "tomato": { cal: 18, protein: 0.9, carbs: 3.9, fat: 0.2 },
  "cucumber": { cal: 15, protein: 0.7, carbs: 3.6, fat: 0.1 },
  "carrot": { cal: 41, protein: 0.9, carbs: 9.6, fat: 0.2 },
  "zucchini": { cal: 17, protein: 1.2, carbs: 3.1, fat: 0.3 },
  "mushroom": { cal: 22, protein: 3.1, carbs: 3.3, fat: 0.3 },
  "avocado": { cal: 160, protein: 2, carbs: 8.5, fat: 14.7 },
  "olive oil": { cal: 884, protein: 0, carbs: 0, fat: 100 },
  "butter": { cal: 717, protein: 0.9, carbs: 0.1, fat: 81 },
  "peanut butter": { cal: 588, protein: 25, carbs: 20, fat: 50 },
  "almonds": { cal: 579, protein: 21, carbs: 22, fat: 50 },
  "walnuts": { cal: 654, protein: 15, carbs: 14, fat: 65 },
  "chia seeds": { cal: 486, protein: 17, carbs: 42, fat: 31 },
  "greek yogurt, plain nonfat": { cal: 59, protein: 10.2, carbs: 3.6, fat: 0.4 },
  "cottage cheese, low fat": { cal: 72, protein: 12, carbs: 3, fat: 1 },
  "milk, 2%": { cal: 50, protein: 3.4, carbs: 4.9, fat: 2 },
  "almond milk, unsweetened": { cal: 15, protein: 0.6, carbs: 0.6, fat: 1.2 },
  "cheddar cheese": { cal: 403, protein: 25, carbs: 1.3, fat: 33 },
  "mozzarella, part skim": { cal: 254, protein: 24, carbs: 2.8, fat: 16 },
  "banana": { cal: 89, protein: 1.1, carbs: 22.8, fat: 0.3 },
  "apple": { cal: 52, protein: 0.3, carbs: 13.8, fat: 0.2 },
  "blueberries": { cal: 57, protein: 0.7, carbs: 14.5, fat: 0.3 },
  "strawberries": { cal: 32, protein: 0.7, carbs: 7.7, fat: 0.3 },
  "orange": { cal: 47, protein: 0.9, carbs: 11.8, fat: 0.1 },
  "honey": { cal: 304, protein: 0.3, carbs: 82.4, fat: 0 },
  "maple syrup": { cal: 260, protein: 0, carbs: 67, fat: 0.2 },
  "pasta, cooked": { cal: 131, protein: 5, carbs: 25, fat: 1.1 },
  "whole wheat pasta, cooked": { cal: 124, protein: 5.3, carbs: 25, fat: 1.1 },
  "corn tortilla": { cal: 218, protein: 5.7, carbs: 44.6, fat: 2.9 },
  "flour tortilla": { cal: 310, protein: 8, carbs: 49, fat: 7.6 },
  "hummus": { cal: 166, protein: 7.9, carbs: 14.3, fat: 9.6 },
  "feta cheese": { cal: 264, protein: 14.2, carbs: 4.1, fat: 21.3 },
  "edamame": { cal: 121, protein: 11, carbs: 10, fat: 5 },
};

// Curated starter suggestions. These are estimates inspired by common
// meal-prep style dishes, not scraped from any specific article — verify
// against the linked (root-domain only) trusted site before relying on them.
// YouTube links use YouTube's real search endpoint with a suggested query,
// since we can't safely guess a specific working video URL.
const RECOMMENDED_MEALS = [
  {
    id: "rec-1",
    name: "High-Protein Turkey Chili",
    mealType: "Dinner",
    sourceLabel: "Skinnytaste",
    sourceUrl: "https://www.skinnytaste.com",
    youtubeQuery: "high protein turkey chili meal prep",
    perServing: { cal: 380, protein: 35, carbs: 30, fat: 12 },
    prepTimeMin: 10,
    cookTimeMin: 30,
    proteinTypes: ["turkey"],
    searchKeywords: ["ground turkey", "beans", "tomatoes", "chili"],
    steps: [
      "Brown the ground turkey with diced onion and garlic.",
      "Stir in beans, diced tomatoes, and chili seasoning; simmer 20-25 minutes.",
      "Cool slightly, then portion into containers.",
    ],
  },
  {
    id: "rec-2",
    name: "Greek Chicken & Quinoa Bowl",
    mealType: "Lunch",
    sourceLabel: "The Clean Eating Couple",
    sourceUrl: "https://www.thecleaneatingcouple.com",
    youtubeQuery: "greek chicken quinoa meal prep bowl",
    perServing: { cal: 450, protein: 38, carbs: 42, fat: 14 },
    prepTimeMin: 15,
    cookTimeMin: 20,
    proteinTypes: ["chicken"],
    searchKeywords: ["chicken breast", "quinoa", "vegetables"],
    steps: [
      "Cook quinoa according to package directions.",
      "Season and grill or pan-sear the chicken; slice.",
      "Assemble bowls with quinoa, chicken, and vegetables; portion into containers.",
    ],
  },
  {
    id: "rec-3",
    name: "Overnight Oats with Berries",
    mealType: "Breakfast",
    sourceLabel: "Eating Bird Food",
    sourceUrl: "https://www.eatingbirdfood.com",
    youtubeQuery: "high protein overnight oats meal prep",
    perServing: { cal: 320, protein: 18, carbs: 45, fat: 8 },
    prepTimeMin: 10,
    cookTimeMin: 0,
    proteinTypes: ["dairy"],
    searchKeywords: ["oats", "yogurt", "milk", "berries"],
    steps: [
      "Combine oats, milk, and yogurt in a jar.",
      "Stir in berries and a sweetener of choice.",
      "Refrigerate overnight; portion into containers.",
    ],
  },
  {
    id: "rec-4",
    name: "Sheet Pan Salmon & Veggies",
    mealType: "Dinner",
    sourceLabel: "Budget Bytes",
    sourceUrl: "https://www.budgetbytes.com",
    youtubeQuery: "sheet pan salmon meal prep",
    perServing: { cal: 420, protein: 34, carbs: 25, fat: 20 },
    prepTimeMin: 10,
    cookTimeMin: 20,
    proteinTypes: ["fish"],
    searchKeywords: ["salmon", "vegetables"],
    steps: [
      "Preheat the oven and arrange salmon and chopped vegetables on a sheet pan.",
      "Season with oil, salt, and pepper.",
      "Roast until the salmon flakes easily; portion into containers.",
    ],
  },
  {
    id: "rec-5",
    name: "Black Bean & Sweet Potato Bowl",
    mealType: "Lunch",
    sourceLabel: "Minimalist Baker",
    sourceUrl: "https://minimalistbaker.com",
    youtubeQuery: "black bean sweet potato meal prep bowl",
    perServing: { cal: 400, protein: 15, carbs: 65, fat: 10 },
    prepTimeMin: 15,
    cookTimeMin: 25,
    proteinTypes: ["plantBased"],
    searchKeywords: ["black beans", "sweet potato"],
    steps: [
      "Roast cubed sweet potato until tender.",
      "Warm black beans with cumin and lime.",
      "Combine with a grain of choice; portion into containers.",
    ],
  },
  {
    id: "rec-6",
    name: "Egg White & Veggie Muffins",
    mealType: "Breakfast",
    sourceLabel: "iFOODreal",
    sourceUrl: "https://ifoodreal.com",
    youtubeQuery: "egg white veggie muffins meal prep",
    perServing: { cal: 180, protein: 20, carbs: 8, fat: 7 },
    prepTimeMin: 10,
    cookTimeMin: 20,
    proteinTypes: ["egg"],
    searchKeywords: ["egg whites", "vegetables"],
    steps: [
      "Whisk egg whites with chopped vegetables.",
      "Pour into a greased muffin tin.",
      "Bake until set; portion into containers.",
    ],
  },
  {
    id: "rec-7",
    name: "Ground Turkey Burrito Bowl",
    mealType: "Dinner",
    sourceLabel: "The Recipe Critic",
    sourceUrl: "https://therecipecritic.com",
    youtubeQuery: "ground turkey burrito bowl meal prep",
    perServing: { cal: 480, protein: 36, carbs: 48, fat: 15 },
    prepTimeMin: 10,
    cookTimeMin: 20,
    proteinTypes: ["turkey"],
    searchKeywords: ["ground turkey", "rice", "black beans"],
    steps: [
      "Brown the ground turkey with taco seasoning.",
      "Cook rice and warm black beans.",
      "Assemble bowls with turkey, rice, beans, and toppings; portion into containers.",
    ],
  },
  {
    id: "rec-8",
    name: "Greek Yogurt Protein Parfait",
    mealType: "Snack",
    sourceLabel: "Gimme Delicious",
    sourceUrl: "https://gimmedelicious.com",
    youtubeQuery: "greek yogurt protein parfait meal prep",
    perServing: { cal: 220, protein: 20, carbs: 24, fat: 5 },
    prepTimeMin: 10,
    cookTimeMin: 0,
    proteinTypes: ["dairy"],
    searchKeywords: ["greek yogurt", "granola", "berries"],
    steps: [
      "Layer Greek yogurt with granola and berries.",
      "Repeat layers as desired.",
      "Portion into containers and refrigerate.",
    ],
  },
  {
    id: "rec-9",
    name: "Shrimp & Broccoli Stir Fry",
    mealType: "Dinner",
    sourceLabel: "Damn Delicious",
    sourceUrl: "https://damndelicious.net",
    youtubeQuery: "shrimp broccoli stir fry meal prep",
    perServing: { cal: 350, protein: 30, carbs: 28, fat: 12 },
    prepTimeMin: 10,
    cookTimeMin: 15,
    proteinTypes: ["fish"],
    searchKeywords: ["shrimp", "broccoli", "rice"],
    steps: [
      "Saute shrimp until pink; set aside.",
      "Stir-fry broccoli and garlic until crisp-tender.",
      "Combine with sauce and shrimp; portion into containers.",
    ],
  },
  {
    id: "rec-10",
    name: "Almond Butter Energy Bites",
    mealType: "Snack",
    sourceLabel: "Cookie and Kate",
    sourceUrl: "https://cookieandkate.com",
    youtubeQuery: "almond butter energy bites no bake",
    perServing: { cal: 150, protein: 5, carbs: 16, fat: 8 },
    prepTimeMin: 15,
    cookTimeMin: 0,
    proteinTypes: ["plantBased"],
    searchKeywords: ["almond butter", "oats"],
    steps: [
      "Mix almond butter, oats, and honey.",
      "Roll into balls.",
      "Refrigerate and portion into containers.",
    ],
  },
  {
    id: "rec-11",
    name: "Buffalo Chicken Meal Prep Bowls",
    mealType: "Lunch",
    sourceLabel: "Well Plated",
    sourceUrl: "https://www.wellplated.com",
    youtubeQuery: "buffalo chicken meal prep bowls",
    perServing: { cal: 420, protein: 40, carbs: 35, fat: 14 },
    prepTimeMin: 15,
    cookTimeMin: 25,
    proteinTypes: ["chicken"],
    searchKeywords: ["chicken breast", "rice", "buffalo sauce", "celery", "carrots"],
    steps: [
      "Cook rice according to package directions.",
      "Bake or shred chicken and toss with buffalo sauce.",
      "Assemble bowls with rice, chicken, celery, and carrots; portion into containers.",
    ],
  },
  {
    id: "rec-12",
    name: "Honey Garlic Chicken & Broccoli",
    mealType: "Dinner",
    sourceLabel: "The Recipe Critic",
    sourceUrl: "https://therecipecritic.com",
    youtubeQuery: "honey garlic chicken broccoli meal prep",
    perServing: { cal: 440, protein: 38, carbs: 40, fat: 12 },
    prepTimeMin: 10,
    cookTimeMin: 20,
    proteinTypes: ["chicken"],
    searchKeywords: ["chicken thigh", "broccoli", "honey garlic sauce", "rice"],
    steps: [
      "Sear diced chicken thighs until browned.",
      "Add broccoli and a honey garlic sauce; simmer until glazed.",
      "Serve over rice; portion into containers.",
    ],
  },
  {
    id: "rec-13",
    name: "Chicken Fajita Bowls",
    mealType: "Lunch",
    sourceLabel: "Gimme Delicious",
    sourceUrl: "https://gimmedelicious.com",
    youtubeQuery: "chicken fajita meal prep bowls",
    perServing: { cal: 400, protein: 35, carbs: 38, fat: 11 },
    prepTimeMin: 15,
    cookTimeMin: 15,
    proteinTypes: ["chicken"],
    searchKeywords: ["chicken breast", "bell pepper", "onion", "rice", "fajita seasoning"],
    steps: [
      "Saute sliced chicken breast with bell peppers, onion, and fajita seasoning.",
      "Cook rice.",
      "Combine and portion into containers.",
    ],
  },
  {
    id: "rec-14",
    name: "BBQ Chicken Sweet Potato Bowls",
    mealType: "Dinner",
    sourceLabel: "Budget Bytes",
    sourceUrl: "https://www.budgetbytes.com",
    youtubeQuery: "bbq chicken sweet potato meal prep bowl",
    perServing: { cal: 410, protein: 34, carbs: 42, fat: 10 },
    prepTimeMin: 10,
    cookTimeMin: 30,
    proteinTypes: ["chicken"],
    searchKeywords: ["chicken breast", "sweet potato", "bbq sauce"],
    steps: [
      "Bake sweet potato cubes until tender.",
      "Shred cooked chicken and toss with BBQ sauce.",
      "Combine and portion into containers.",
    ],
  },
  {
    id: "rec-15",
    name: "Beef and Broccoli Stir Fry",
    mealType: "Dinner",
    sourceLabel: "Damn Delicious",
    sourceUrl: "https://damndelicious.net",
    youtubeQuery: "beef and broccoli meal prep",
    perServing: { cal: 430, protein: 32, carbs: 30, fat: 18 },
    prepTimeMin: 10,
    cookTimeMin: 15,
    proteinTypes: ["beef"],
    searchKeywords: ["beef", "broccoli", "rice", "soy sauce"],
    steps: [
      "Sear thin-sliced beef until browned; set aside.",
      "Stir-fry broccoli and garlic until crisp-tender.",
      "Combine with a soy-based sauce and beef; serve over rice, portion into containers.",
    ],
  },
  {
    id: "rec-16",
    name: "Taco Beef Rice Bowls",
    mealType: "Lunch",
    sourceLabel: "The Recipe Critic",
    sourceUrl: "https://therecipecritic.com",
    youtubeQuery: "taco beef rice meal prep bowls",
    perServing: { cal: 450, protein: 30, carbs: 40, fat: 16 },
    prepTimeMin: 10,
    cookTimeMin: 15,
    proteinTypes: ["beef"],
    searchKeywords: ["ground beef", "rice", "taco seasoning"],
    steps: [
      "Brown ground beef with taco seasoning.",
      "Cook rice.",
      "Assemble bowls with beef, rice, and toppings; portion into containers.",
    ],
  },
  {
    id: "rec-17",
    name: "Classic Beef Chili",
    mealType: "Dinner",
    sourceLabel: "Budget Bytes",
    sourceUrl: "https://www.budgetbytes.com",
    youtubeQuery: "classic beef chili meal prep",
    perServing: { cal: 400, protein: 28, carbs: 32, fat: 16 },
    prepTimeMin: 10,
    cookTimeMin: 35,
    proteinTypes: ["beef"],
    searchKeywords: ["ground beef", "beans", "tomatoes", "chili"],
    steps: [
      "Brown ground beef with diced onion.",
      "Add beans, tomatoes, and chili seasoning; simmer.",
      "Portion into containers.",
    ],
  },
  {
    id: "rec-18",
    name: "Pork Tenderloin with Roasted Veggies",
    mealType: "Dinner",
    sourceLabel: "Half Baked Harvest",
    sourceUrl: "https://www.halfbakedharvest.com",
    youtubeQuery: "pork tenderloin meal prep roasted vegetables",
    perServing: { cal: 380, protein: 36, carbs: 22, fat: 14 },
    prepTimeMin: 15,
    cookTimeMin: 30,
    proteinTypes: ["pork"],
    searchKeywords: ["pork tenderloin", "vegetables"],
    steps: [
      "Season and roast pork tenderloin until cooked through.",
      "Roast a tray of mixed vegetables alongside.",
      "Slice pork and portion into containers.",
    ],
  },
  {
    id: "rec-19",
    name: "Pulled Pork Sweet Potato Bowls",
    mealType: "Lunch",
    sourceLabel: "The Recipe Critic",
    sourceUrl: "https://therecipecritic.com",
    youtubeQuery: "pulled pork sweet potato meal prep",
    perServing: { cal: 430, protein: 32, carbs: 40, fat: 14 },
    prepTimeMin: 15,
    cookTimeMin: 240,
    proteinTypes: ["pork"],
    searchKeywords: ["pork shoulder", "sweet potato"],
    steps: [
      "Slow-cook pork shoulder until tender, then shred.",
      "Roast sweet potato cubes.",
      "Combine with a light sauce; portion into containers.",
    ],
  },
  {
    id: "rec-20",
    name: "Turkey Meatballs with Zucchini Noodles",
    mealType: "Dinner",
    sourceLabel: "Skinnytaste",
    sourceUrl: "https://www.skinnytaste.com",
    youtubeQuery: "turkey meatballs zucchini noodles meal prep",
    perServing: { cal: 360, protein: 34, carbs: 14, fat: 18 },
    prepTimeMin: 15,
    cookTimeMin: 20,
    proteinTypes: ["turkey"],
    searchKeywords: ["ground turkey", "zucchini noodles", "marinara"],
    steps: [
      "Mix and bake ground turkey meatballs.",
      "Spiralize zucchini into noodles.",
      "Toss noodles with marinara and meatballs; portion into containers.",
    ],
  },
  {
    id: "rec-21",
    name: "Garlic Butter Shrimp & Rice",
    mealType: "Lunch",
    sourceLabel: "Damn Delicious",
    sourceUrl: "https://damndelicious.net",
    youtubeQuery: "garlic butter shrimp rice meal prep",
    perServing: { cal: 380, protein: 30, carbs: 38, fat: 12 },
    prepTimeMin: 10,
    cookTimeMin: 10,
    proteinTypes: ["fish"],
    searchKeywords: ["shrimp", "rice", "garlic butter"],
    steps: [
      "Saute shrimp in garlic butter until pink.",
      "Cook rice.",
      "Combine and portion into containers.",
    ],
  },
  {
    id: "rec-22",
    name: "Baked Cod with Vegetables",
    mealType: "Dinner",
    sourceLabel: "Feasting at Home",
    sourceUrl: "https://www.feastingathome.com",
    youtubeQuery: "baked cod meal prep vegetables",
    perServing: { cal: 340, protein: 32, carbs: 20, fat: 12 },
    prepTimeMin: 10,
    cookTimeMin: 20,
    proteinTypes: ["fish"],
    searchKeywords: ["cod", "vegetables"],
    steps: [
      "Season cod fillets and arrange with a tray of mixed vegetables.",
      "Roast until the fish flakes easily.",
      "Portion into containers.",
    ],
  },
  {
    id: "rec-23",
    name: "Tuna Salad Lettuce Wraps",
    mealType: "Lunch",
    sourceLabel: "Eating Bird Food",
    sourceUrl: "https://www.eatingbirdfood.com",
    youtubeQuery: "tuna salad lettuce wraps meal prep",
    perServing: { cal: 280, protein: 28, carbs: 8, fat: 14 },
    prepTimeMin: 10,
    cookTimeMin: 0,
    proteinTypes: ["fish"],
    searchKeywords: ["tuna", "lettuce", "celery"],
    steps: [
      "Mix canned tuna with a light dressing and chopped vegetables.",
      "Spoon into lettuce leaves just before eating.",
      "Store tuna mixture and lettuce separately, portioned into containers.",
    ],
  },
  {
    id: "rec-24",
    name: "Breakfast Burrito Bowls",
    mealType: "Breakfast",
    sourceLabel: "The Clean Eating Couple",
    sourceUrl: "https://www.thecleaneatingcouple.com",
    youtubeQuery: "breakfast burrito bowl meal prep",
    perServing: { cal: 350, protein: 22, carbs: 30, fat: 15 },
    prepTimeMin: 10,
    cookTimeMin: 15,
    proteinTypes: ["egg", "plantBased"],
    searchKeywords: ["eggs", "black beans", "avocado", "potatoes"],
    steps: [
      "Scramble eggs and warm black beans.",
      "Dice avocado and roast potatoes.",
      "Combine into bowls; portion into containers.",
    ],
  },
  {
    id: "rec-25",
    name: "Cottage Cheese Bowl with Fruit",
    mealType: "Snack",
    sourceLabel: "Eating Bird Food",
    sourceUrl: "https://www.eatingbirdfood.com",
    youtubeQuery: "cottage cheese bowl meal prep",
    perServing: { cal: 220, protein: 22, carbs: 20, fat: 5 },
    prepTimeMin: 5,
    cookTimeMin: 0,
    proteinTypes: ["dairy"],
    searchKeywords: ["cottage cheese", "fruit", "honey"],
    steps: [
      "Portion cottage cheese into containers.",
      "Top with fresh or frozen fruit and a drizzle of honey just before eating.",
    ],
  },
  {
    id: "rec-26",
    name: "Veggie Tofu Stir Fry",
    mealType: "Dinner",
    sourceLabel: "Minimalist Baker",
    sourceUrl: "https://minimalistbaker.com",
    youtubeQuery: "tofu vegetable stir fry meal prep",
    perServing: { cal: 360, protein: 20, carbs: 34, fat: 16 },
    prepTimeMin: 15,
    cookTimeMin: 15,
    proteinTypes: ["plantBased"],
    searchKeywords: ["tofu", "vegetables", "rice", "soy sauce"],
    steps: [
      "Press and pan-sear cubed tofu until golden.",
      "Stir-fry mixed vegetables.",
      "Combine with a soy-ginger sauce; serve over rice, portion into containers.",
    ],
  },
  {
    id: "rec-27",
    name: "Chickpea Salad Bowls",
    mealType: "Lunch",
    sourceLabel: "Cookie and Kate",
    sourceUrl: "https://cookieandkate.com",
    youtubeQuery: "chickpea salad meal prep bowls",
    perServing: { cal: 380, protein: 16, carbs: 46, fat: 14 },
    prepTimeMin: 15,
    cookTimeMin: 0,
    proteinTypes: ["plantBased"],
    searchKeywords: ["chickpeas", "vegetables", "tahini"],
    steps: [
      "Combine chickpeas, chopped vegetables, and a lemon-tahini dressing.",
      "Portion into containers.",
    ],
  },
  {
    id: "rec-28",
    name: "Lentil Soup",
    mealType: "Dinner",
    sourceLabel: "Feasting at Home",
    sourceUrl: "https://www.feastingathome.com",
    youtubeQuery: "lentil soup meal prep",
    perServing: { cal: 320, protein: 18, carbs: 48, fat: 6 },
    prepTimeMin: 15,
    cookTimeMin: 35,
    proteinTypes: ["plantBased"],
    searchKeywords: ["lentils", "carrots", "celery", "broth"],
    steps: [
      "Saute onion, carrot, and celery.",
      "Add lentils, broth, and spices; simmer until tender.",
      "Portion into containers.",
    ],
  },
];

const ACTIVITY_LEVELS = {
  sedentary: { label: "Sedentary (little/no exercise)", mult: 1.2 },
  light: { label: "Lightly active (1-3 days/wk)", mult: 1.375 },
  moderate: { label: "Moderately active (3-5 days/wk)", mult: 1.55 },
  active: { label: "Very active (6-7 days/wk)", mult: 1.725 },
  athlete: { label: "Athlete (2x/day training)", mult: 1.9 },
};

const RECIPE_CATEGORIES = ["Breakfast", "Lunch", "Dinner", "Snack", "Other"];

const UNIT_TO_GRAMS = { g: 1, kg: 1000, oz: 28.3495, lb: 453.592 };

// Protein-type taxonomy for the Meal Prep Planner's protein filter and the
// Recommended tab's search. "mine" recipes are classified by matching their
// ingredient names against this map; Recommended entries are tagged directly.
const PROTEIN_TYPES = {
  any: "Any protein",
  chicken: "Chicken",
  beef: "Beef",
  pork: "Pork",
  turkey: "Turkey",
  fish: "Fish & seafood",
  egg: "Egg",
  plantBased: "Plant-based (tofu, beans, lentils)",
  dairy: "Dairy (yogurt, cottage cheese)",
};

const FOOD_PROTEIN_TYPE = {
  "chicken breast, cooked": "chicken",
  "chicken thigh, cooked": "chicken",
  "ground beef 90/10, cooked": "beef",
  "ground turkey, cooked": "turkey",
  "pork tenderloin, cooked": "pork",
  "salmon, cooked": "fish",
  "tilapia, cooked": "fish",
  "shrimp, cooked": "fish",
  "cod, cooked": "fish",
  "tuna, canned in water": "fish",
  "egg, whole": "egg",
  "egg white": "egg",
  "tofu, firm": "plantBased",
  "black beans, cooked": "plantBased",
  "chickpeas, cooked": "plantBased",
  "lentils, cooked": "plantBased",
  "edamame": "plantBased",
  "greek yogurt, plain nonfat": "dairy",
  "cottage cheese, low fat": "dairy",
};

// Diet filters for the Meal Prep Planner. Thresholds are deliberately
// simplified (this app can't model diet phases or exact clinical protocols)
// but are grounded in how each diet is commonly and consistently described:
//  - Keto: ~70-75% of calories from fat, 20-25% protein, 5-10% carbs.
//  - Atkins: low-carb/higher-protein; historically phased (induction ~20g
//    net carbs/day up to a higher maintenance intake), which a per-recipe
//    filter can't represent, so this approximates the general approach.
//  - Low carb: a commonly used clinical threshold is roughly <=26% of
//    calories from carbohydrate.
//  - Volumetrics ("high volume, low calorie"): ranks/filters by energy
//    density (calories per gram) rather than a macro ratio, per Dr. Barbara
//    Rolls' Volumetrics research — low-density foods (produce, lean protein,
//    broth-based dishes) are roughly under ~1.5-2 kcal/g, vs. energy-dense
//    foods (oils, nuts, fried food) well above that.
//  - Carnivore: animal products only (meat, poultry, fish, eggs, dairy) with
//    no plant foods; checked ingredient-by-ingredient against the food
//    database below, so it only works for known ingredients.
const DIETS = {
  any: {
    label: "No specific diet",
    description: "No dietary restrictions — matches any recipe.",
  },
  keto: {
    label: "Keto (ketogenic)",
    description: "Very low carb, high fat: roughly 70-75% of calories from fat, 20-25% from protein, and 5-10% from carbs.",
    kind: "macroRatio",
    maxCarbPct: 10,
    minFatPct: 65,
  },
  atkins: {
    label: "Atkins-style (low carb)",
    description: "Low-carb, higher-protein eating in the style of the Atkins diet. This approximates the general approach — not the specific induction/maintenance phase targets — by keeping carbs low.",
    kind: "macroRatio",
    maxCarbPct: 15,
  },
  lowcarb: {
    label: "Low carb",
    description: "General low-carb eating: no more than about 26% of calories from carbohydrate, a commonly used low-carb threshold.",
    kind: "macroRatio",
    maxCarbPct: 26,
  },
  volumetrics: {
    label: "High volume, low calorie",
    description: "Favors lower energy-density recipes (more food weight per calorie, like vegetables, lean protein, and broth-based dishes) so portions feel larger for the same calories. Estimated as calories per gram across the whole recipe, so it only works for recipes with a real ingredient list (not the Recommended tab's placeholder entries).",
    kind: "density",
    maxKcalPerGram: 1.6,
  },
  carnivore: {
    label: "Carnivore",
    description: "Animal products only — meat, poultry, fish, eggs, and dairy — with no vegetables, fruit, grains, or legumes. Checked ingredient-by-ingredient against the built-in food database, so it only works for recipes built from known ingredients (not custom or placeholder ones).",
    kind: "ingredient",
  },
};

// Which FOOD_DB entries count as animal-derived, for the Carnivore diet filter.
const ANIMAL_FOOD_KEYS = new Set([
  "chicken breast, cooked",
  "chicken thigh, cooked",
  "ground beef 90/10, cooked",
  "ground turkey, cooked",
  "salmon, cooked",
  "tilapia, cooked",
  "shrimp, cooked",
  "egg, whole",
  "egg white",
  "greek yogurt, plain nonfat",
  "cottage cheese, low fat",
  "milk, 2%",
  "cheddar cheese",
  "mozzarella, part skim",
  "feta cheese",
  "butter",
]);

// Ingredients that are widely available pre-chopped or frozen at the
// grocery store, used to surface time-saving tips for a given recipe.
const FREEZABLE_OR_PRECUT_INGREDIENTS = new Set([
  "broccoli, cooked",
  "spinach, raw",
  "kale, raw",
  "bell pepper",
  "onion",
  "carrot",
  "zucchini",
  "mushroom",
  "edamame",
  "blueberries",
  "strawberries",
  "banana",
  "shrimp, cooked",
]);

const GENERIC_MEAL_PREP_TIPS = [
  "Cook proteins in one big batch, then portion once they've cooled — reheats better than cooking a whole tray fresh each day.",
  "Let food cool to room temperature before sealing containers; sealing while hot traps steam and makes everything soggy.",
  "Cook grains and starches slightly under, since they keep softening a bit as they reheat.",
  "Store sauces or dressings separately and add them at serving time so greens or grains don't get soggy in the fridge.",
  "Label containers with the date — most meal-prepped dishes keep 3-4 days refrigerated, or 2-3 months frozen.",
];
