// Built-in nutrition database — approximate values per 100g, for estimation only.
// Sources: general USDA-style reference values. Always verify against packaging
// or an official database for medical/diet-critical use.
const FOOD_DB = {
  "chicken breast, cooked": { cal: 165, protein: 31, carbs: 0, fat: 3.6 },
  "chicken thigh, cooked": { cal: 209, protein: 26, carbs: 0, fat: 10.9 },
  "ground beef 90/10, cooked": { cal: 217, protein: 26, carbs: 0, fat: 12 },
  "ground turkey, cooked": { cal: 176, protein: 27, carbs: 0, fat: 8 },
  "pork tenderloin, cooked": { cal: 143, protein: 26, carbs: 0, fat: 3.5 },
  "salmon, cooked": { cal: 206, protein: 22, carbs: 0, fat: 13 },
  "tilapia, cooked": { cal: 128, protein: 26, carbs: 0, fat: 2.7 },
  "cod, cooked": { cal: 105, protein: 23, carbs: 0, fat: 0.9 },
  "tuna, canned in water": { cal: 116, protein: 26, carbs: 0, fat: 0.8 },
  "shrimp, cooked": { cal: 99, protein: 24, carbs: 0.2, fat: 0.3 },
  "egg, whole": { cal: 155, protein: 13, carbs: 1.1, fat: 11 },
  "egg white": { cal: 52, protein: 11, carbs: 0.7, fat: 0.2 },
  "tofu, firm": { cal: 144, protein: 17, carbs: 3, fat: 8 },
  "black beans, cooked": { cal: 132, protein: 8.9, carbs: 23.7, fat: 0.5 },
  "chickpeas, cooked": { cal: 164, protein: 8.9, carbs: 27.4, fat: 2.6 },
  "lentils, cooked": { cal: 116, protein: 9, carbs: 20, fat: 0.4 },
  "white rice, cooked": { cal: 130, protein: 2.7, carbs: 28, fat: 0.3 },
  "brown rice, cooked": { cal: 123, protein: 2.7, carbs: 25.6, fat: 1 },
  "quinoa, cooked": { cal: 120, protein: 4.4, carbs: 21.3, fat: 1.9 },
  "sweet potato, baked": { cal: 90, protein: 2, carbs: 20.7, fat: 0.2 },
  "potato, baked": { cal: 93, protein: 2.5, carbs: 21.2, fat: 0.1 },
  "oats, dry": { cal: 389, protein: 16.9, carbs: 66.3, fat: 6.9 },
  "whole wheat bread": { cal: 247, protein: 13, carbs: 41, fat: 3.4 },
  "broccoli, cooked": { cal: 35, protein: 2.4, carbs: 7.2, fat: 0.4 },
  "spinach, raw": { cal: 23, protein: 2.9, carbs: 3.6, fat: 0.4 },
  "kale, raw": { cal: 49, protein: 4.3, carbs: 8.8, fat: 0.9 },
  "bell pepper": { cal: 31, protein: 1, carbs: 6, fat: 0.3 },
  "onion": { cal: 40, protein: 1.1, carbs: 9.3, fat: 0.1 },
  "garlic": { cal: 149, protein: 6.4, carbs: 33, fat: 0.5 },
  "tomato": { cal: 18, protein: 0.9, carbs: 3.9, fat: 0.2 },
  "cucumber": { cal: 15, protein: 0.7, carbs: 3.6, fat: 0.1 },
  "carrot": { cal: 41, protein: 0.9, carbs: 9.6, fat: 0.2 },
  "zucchini": { cal: 17, protein: 1.2, carbs: 3.1, fat: 0.3 },
  "mushroom": { cal: 22, protein: 3.1, carbs: 3.3, fat: 0.3 },
  "avocado": { cal: 160, protein: 2, carbs: 8.5, fat: 14.7 },
  "olive oil": { cal: 884, protein: 0, carbs: 0, fat: 100 },
  "butter": { cal: 717, protein: 0.9, carbs: 0.1, fat: 81 },
  "peanut butter": { cal: 588, protein: 25, carbs: 20, fat: 50 },
  "almonds": { cal: 579, protein: 21, carbs: 22, fat: 50 },
  "walnuts": { cal: 654, protein: 15, carbs: 14, fat: 65 },
  "chia seeds": { cal: 486, protein: 17, carbs: 42, fat: 31 },
  "greek yogurt, plain nonfat": { cal: 59, protein: 10.2, carbs: 3.6, fat: 0.4 },
  "cottage cheese, low fat": { cal: 72, protein: 12, carbs: 3, fat: 1 },
  "milk, 2%": { cal: 50, protein: 3.4, carbs: 4.9, fat: 2 },
  "almond milk, unsweetened": { cal: 15, protein: 0.6, carbs: 0.6, fat: 1.2 },
  "cheddar cheese": { cal: 403, protein: 25, carbs: 1.3, fat: 33 },
  "mozzarella, part skim": { cal: 254, protein: 24, carbs: 2.8, fat: 16 },
  "banana": { cal: 89, protein: 1.1, carbs: 22.8, fat: 0.3 },
  "apple": { cal: 52, protein: 0.3, carbs: 13.8, fat: 0.2 },
  "blueberries": { cal: 57, protein: 0.7, carbs: 14.5, fat: 0.3 },
  "strawberries": { cal: 32, protein: 0.7, carbs: 7.7, fat: 0.3 },
  "orange": { cal: 47, protein: 0.9, carbs: 11.8, fat: 0.1 },
  "honey": { cal: 304, protein: 0.3, carbs: 82.4, fat: 0 },
  "maple syrup": { cal: 260, protein: 0, carbs: 67, fat: 0.2 },
  "pasta, cooked": { cal: 131, protein: 5, carbs: 25, fat: 1.1 },
  "whole wheat pasta, cooked": { cal: 124, protein: 5.3, carbs: 25, fat: 1.1 },
  "corn tortilla": { cal: 218, protein: 5.7, carbs: 44.6, fat: 2.9 },
  "flour tortilla": { cal: 310, protein: 8, carbs: 49, fat: 7.6 },
  "hummus": { cal: 166, protein: 7.9, carbs: 14.3, fat: 9.6 },
  "feta cheese": { cal: 264, protein: 14.2, carbs: 4.1, fat: 21.3 },
  "edamame": { cal: 121, protein: 11, carbs: 10, fat: 5 },
};

// Trusted recipe sites. A static page can't fetch or scrape these (browsers
// block cross-origin reads), so instead we link into each site's own search.
// "wp" = WordPress search (/?s=), "q" = /search?q= (Allrecipes and its
// sister sites).
const RECIPE_SITES = {
  allrecipes: { label: "Allrecipes", home: "https://www.allrecipes.com", search: "q" },
  budgetbytes: { label: "Budget Bytes", home: "https://www.budgetbytes.com", search: "wp" },
  cafedelites: { label: "Cafe Delites", home: "https://cafedelites.com", search: "wp" },
  cleaneatingcouple: { label: "The Clean Eating Couple", home: "https://www.thecleaneatingcouple.com", search: "wp" },
  cookieandkate: { label: "Cookie and Kate", home: "https://cookieandkate.com", search: "wp" },
  damndelicious: { label: "Damn Delicious", home: "https://damndelicious.net", search: "wp" },
  eatingbirdfood: { label: "Eating Bird Food", home: "https://www.eatingbirdfood.com", search: "wp" },
  eatingwell: { label: "EatingWell", home: "https://www.eatingwell.com", search: "q" },
  feastingathome: { label: "Feasting at Home", home: "https://www.feastingathome.com", search: "wp" },
  gimmedelicious: { label: "Gimme Delicious", home: "https://gimmedelicious.com", search: "wp" },
  halfbakedharvest: { label: "Half Baked Harvest", home: "https://www.halfbakedharvest.com", search: "wp" },
  ifoodreal: { label: "iFOODreal", home: "https://ifoodreal.com", search: "wp" },
  loveandlemons: { label: "Love and Lemons", home: "https://www.loveandlemons.com", search: "wp" },
  minimalistbaker: { label: "Minimalist Baker", home: "https://minimalistbaker.com", search: "wp" },
  natashaskitchen: { label: "Natasha's Kitchen", home: "https://natashaskitchen.com", search: "wp" },
  pinchofyum: { label: "Pinch of Yum", home: "https://pinchofyum.com", search: "wp" },
  recipecritic: { label: "The Recipe Critic", home: "https://therecipecritic.com", search: "wp" },
  recipetineats: { label: "RecipeTin Eats", home: "https://www.recipetineats.com", search: "wp" },
  seriouseats: { label: "Serious Eats", home: "https://www.seriouseats.com", search: "q" },
  simplyrecipes: { label: "Simply Recipes", home: "https://www.simplyrecipes.com", search: "q" },
  skinnytaste: { label: "Skinnytaste", home: "https://www.skinnytaste.com", search: "wp" },
  wellplated: { label: "Well Plated", home: "https://www.wellplated.com", search: "wp" },
};

function siteSearchUrl(siteKey, query) {
  const site = RECIPE_SITES[siteKey];
  const q = encodeURIComponent(query);
  return site.search === "q" ? `${site.home}/search?q=${q}` : `${site.home}/?s=${q}`;
}

// Words used to build a cross-site search query from the planner's filters.
const PROTEIN_SEARCH_TERMS = {
  chicken: "chicken",
  beef: "beef",
  pork: "pork",
  turkey: "turkey",
  fish: "seafood",
  egg: "egg",
  plantBased: "vegetarian",
  dairy: "high protein",
};

const DIET_SEARCH_TERMS = {
  keto: "keto",
  atkins: "low carb",
  lowcarb: "low carb",
  volumetrics: "low calorie",
  carnivore: "carnivore",
};

// Curated starter recipes with estimated macros, inspired by common
// meal-prep dishes rather than copied from a specific article. Each one's
// link searches its site for the dish so you can find the real recipe and
// check the numbers. YouTube links use YouTube's own search for the same
// reason: we can't safely guess a specific working video URL.
const RECOMMENDED_MEALS = [
  {
    id: "rec-1",
    name: "High-Protein Turkey Chili",
    mealType: "Dinner",
    site: "skinnytaste",
    youtubeQuery: "high protein turkey chili meal prep",
    perServing: { cal: 380, protein: 35, carbs: 30, fat: 12 },
    prepTimeMin: 10,
    cookTimeMin: 30,
    proteinTypes: ["turkey"],
    searchKeywords: ["ground turkey", "beans", "tomatoes", "chili"],
    steps: [
      "Brown the ground turkey with diced onion and garlic.",
      "Stir in beans, diced tomatoes, and chili seasoning; simmer 20-25 minutes.",
      "Cool slightly, then portion into containers.",
    ],
  },
  {
    id: "rec-2",
    name: "Greek Chicken & Quinoa Bowl",
    mealType: "Lunch",
    site: "cleaneatingcouple",
    youtubeQuery: "greek chicken quinoa meal prep bowl",
    perServing: { cal: 450, protein: 38, carbs: 42, fat: 14 },
    prepTimeMin: 15,
    cookTimeMin: 20,
    proteinTypes: ["chicken"],
    searchKeywords: ["chicken breast", "quinoa", "vegetables"],
    steps: [
      "Cook quinoa according to package directions.",
      "Season and grill or pan-sear the chicken; slice.",
      "Assemble bowls with quinoa, chicken, and vegetables; portion into containers.",
    ],
  },
  {
    id: "rec-3",
    name: "Overnight Oats with Berries",
    mealType: "Breakfast",
    site: "eatingbirdfood",
    youtubeQuery: "high protein overnight oats meal prep",
    perServing: { cal: 320, protein: 18, carbs: 45, fat: 8 },
    prepTimeMin: 10,
    cookTimeMin: 0,
    proteinTypes: ["dairy"],
    searchKeywords: ["oats", "yogurt", "milk", "berries"],
    steps: [
      "Combine oats, milk, and yogurt in a jar.",
      "Stir in berries and a sweetener of choice.",
      "Refrigerate overnight; portion into containers.",
    ],
  },
  {
    id: "rec-4",
    name: "Sheet Pan Salmon & Veggies",
    mealType: "Dinner",
    site: "budgetbytes",
    youtubeQuery: "sheet pan salmon meal prep",
    perServing: { cal: 420, protein: 34, carbs: 25, fat: 20 },
    prepTimeMin: 10,
    cookTimeMin: 20,
    proteinTypes: ["fish"],
    searchKeywords: ["salmon", "vegetables"],
    steps: [
      "Preheat the oven and arrange salmon and chopped vegetables on a sheet pan.",
      "Season with oil, salt, and pepper.",
      "Roast until the salmon flakes easily; portion into containers.",
    ],
  },
  {
    id: "rec-5",
    name: "Black Bean & Sweet Potato Bowl",
    mealType: "Lunch",
    site: "minimalistbaker",
    youtubeQuery: "black bean sweet potato meal prep bowl",
    perServing: { cal: 400, protein: 15, carbs: 65, fat: 10 },
    prepTimeMin: 15,
    cookTimeMin: 25,
    proteinTypes: ["plantBased"],
    searchKeywords: ["black beans", "sweet potato"],
    steps: [
      "Roast cubed sweet potato until tender.",
      "Warm black beans with cumin and lime.",
      "Combine with a grain of choice; portion into containers.",
    ],
  },
  {
    id: "rec-6",
    name: "Egg White & Veggie Muffins",
    mealType: "Breakfast",
    site: "ifoodreal",
    youtubeQuery: "egg white veggie muffins meal prep",
    perServing: { cal: 180, protein: 20, carbs: 8, fat: 7 },
    prepTimeMin: 10,
    cookTimeMin: 20,
    proteinTypes: ["egg"],
    searchKeywords: ["egg whites", "vegetables"],
    steps: [
      "Whisk egg whites with chopped vegetables.",
      "Pour into a greased muffin tin.",
      "Bake until set; portion into containers.",
    ],
  },
  {
    id: "rec-7",
    name: "Ground Turkey Burrito Bowl",
    mealType: "Dinner",
    site: "recipecritic",
    youtubeQuery: "ground turkey burrito bowl meal prep",
    perServing: { cal: 480, protein: 36, carbs: 48, fat: 15 },
    prepTimeMin: 10,
    cookTimeMin: 20,
    proteinTypes: ["turkey"],
    searchKeywords: ["ground turkey", "rice", "black beans"],
    steps: [
      "Brown the ground turkey with taco seasoning.",
      "Cook rice and warm black beans.",
      "Assemble bowls with turkey, rice, beans, and toppings; portion into containers.",
    ],
  },
  {
    id: "rec-8",
    name: "Greek Yogurt Protein Parfait",
    mealType: "Snack",
    site: "gimmedelicious",
    youtubeQuery: "greek yogurt protein parfait meal prep",
    perServing: { cal: 220, protein: 20, carbs: 24, fat: 5 },
    prepTimeMin: 10,
    cookTimeMin: 0,
    proteinTypes: ["dairy"],
    searchKeywords: ["greek yogurt", "granola", "berries"],
    steps: [
      "Layer Greek yogurt with granola and berries.",
      "Repeat layers as desired.",
      "Portion into containers and refrigerate.",
    ],
  },
  {
    id: "rec-9",
    name: "Shrimp & Broccoli Stir Fry",
    mealType: "Dinner",
    site: "damndelicious",
    youtubeQuery: "shrimp broccoli stir fry meal prep",
    perServing: { cal: 350, protein: 30, carbs: 28, fat: 12 },
    prepTimeMin: 10,
    cookTimeMin: 15,
    proteinTypes: ["fish"],
    searchKeywords: ["shrimp", "broccoli", "rice"],
    steps: [
      "Saute shrimp until pink; set aside.",
      "Stir-fry broccoli and garlic until crisp-tender.",
      "Combine with sauce and shrimp; portion into containers.",
    ],
  },
  {
    id: "rec-10",
    name: "Almond Butter Energy Bites",
    mealType: "Snack",
    site: "cookieandkate",
    youtubeQuery: "almond butter energy bites no bake",
    perServing: { cal: 150, protein: 5, carbs: 16, fat: 8 },
    prepTimeMin: 15,
    cookTimeMin: 0,
    proteinTypes: ["plantBased"],
    searchKeywords: ["almond butter", "oats"],
    steps: [
      "Mix almond butter, oats, and honey.",
      "Roll into balls.",
      "Refrigerate and portion into containers.",
    ],
  },
  {
    id: "rec-11",
    name: "Buffalo Chicken Meal Prep Bowls",
    mealType: "Lunch",
    site: "wellplated",
    youtubeQuery: "buffalo chicken meal prep bowls",
    perServing: { cal: 420, protein: 40, carbs: 35, fat: 14 },
    prepTimeMin: 15,
    cookTimeMin: 25,
    proteinTypes: ["chicken"],
    searchKeywords: ["chicken breast", "rice", "buffalo sauce", "celery", "carrots"],
    steps: [
      "Cook rice according to package directions.",
      "Bake or shred chicken and toss with buffalo sauce.",
      "Assemble bowls with rice, chicken, celery, and carrots; portion into containers.",
    ],
  },
  {
    id: "rec-12",
    name: "Honey Garlic Chicken & Broccoli",
    mealType: "Dinner",
    site: "recipecritic",
    youtubeQuery: "honey garlic chicken broccoli meal prep",
    perServing: { cal: 440, protein: 38, carbs: 40, fat: 12 },
    prepTimeMin: 10,
    cookTimeMin: 20,
    proteinTypes: ["chicken"],
    searchKeywords: ["chicken thigh", "broccoli", "honey garlic sauce", "rice"],
    steps: [
      "Sear diced chicken thighs until browned.",
      "Add broccoli and a honey garlic sauce; simmer until glazed.",
      "Serve over rice; portion into containers.",
    ],
  },
  {
    id: "rec-13",
    name: "Chicken Fajita Bowls",
    mealType: "Lunch",
    site: "gimmedelicious",
    youtubeQuery: "chicken fajita meal prep bowls",
    perServing: { cal: 400, protein: 35, carbs: 38, fat: 11 },
    prepTimeMin: 15,
    cookTimeMin: 15,
    proteinTypes: ["chicken"],
    searchKeywords: ["chicken breast", "bell pepper", "onion", "rice", "fajita seasoning"],
    steps: [
      "Saute sliced chicken breast with bell peppers, onion, and fajita seasoning.",
      "Cook rice.",
      "Combine and portion into containers.",
    ],
  },
  {
    id: "rec-14",
    name: "BBQ Chicken Sweet Potato Bowls",
    mealType: "Dinner",
    site: "budgetbytes",
    youtubeQuery: "bbq chicken sweet potato meal prep bowl",
    perServing: { cal: 410, protein: 34, carbs: 42, fat: 10 },
    prepTimeMin: 10,
    cookTimeMin: 30,
    proteinTypes: ["chicken"],
    searchKeywords: ["chicken breast", "sweet potato", "bbq sauce"],
    steps: [
      "Bake sweet potato cubes until tender.",
      "Shred cooked chicken and toss with BBQ sauce.",
      "Combine and portion into containers.",
    ],
  },
  {
    id: "rec-15",
    name: "Beef and Broccoli Stir Fry",
    mealType: "Dinner",
    site: "damndelicious",
    youtubeQuery: "beef and broccoli meal prep",
    perServing: { cal: 430, protein: 32, carbs: 30, fat: 18 },
    prepTimeMin: 10,
    cookTimeMin: 15,
    proteinTypes: ["beef"],
    searchKeywords: ["beef", "broccoli", "rice", "soy sauce"],
    steps: [
      "Sear thin-sliced beef until browned; set aside.",
      "Stir-fry broccoli and garlic until crisp-tender.",
      "Combine with a soy-based sauce and beef; serve over rice, portion into containers.",
    ],
  },
  {
    id: "rec-16",
    name: "Taco Beef Rice Bowls",
    mealType: "Lunch",
    site: "recipecritic",
    youtubeQuery: "taco beef rice meal prep bowls",
    perServing: { cal: 450, protein: 30, carbs: 40, fat: 16 },
    prepTimeMin: 10,
    cookTimeMin: 15,
    proteinTypes: ["beef"],
    searchKeywords: ["ground beef", "rice", "taco seasoning"],
    steps: [
      "Brown ground beef with taco seasoning.",
      "Cook rice.",
      "Assemble bowls with beef, rice, and toppings; portion into containers.",
    ],
  },
  {
    id: "rec-17",
    name: "Classic Beef Chili",
    mealType: "Dinner",
    site: "budgetbytes",
    youtubeQuery: "classic beef chili meal prep",
    perServing: { cal: 400, protein: 28, carbs: 32, fat: 16 },
    prepTimeMin: 10,
    cookTimeMin: 35,
    proteinTypes: ["beef"],
    searchKeywords: ["ground beef", "beans", "tomatoes", "chili"],
    steps: [
      "Brown ground beef with diced onion.",
      "Add beans, tomatoes, and chili seasoning; simmer.",
      "Portion into containers.",
    ],
  },
  {
    id: "rec-18",
    name: "Pork Tenderloin with Roasted Veggies",
    mealType: "Dinner",
    site: "halfbakedharvest",
    youtubeQuery: "pork tenderloin meal prep roasted vegetables",
    perServing: { cal: 380, protein: 36, carbs: 22, fat: 14 },
    prepTimeMin: 15,
    cookTimeMin: 30,
    proteinTypes: ["pork"],
    searchKeywords: ["pork tenderloin", "vegetables"],
    steps: [
      "Season and roast pork tenderloin until cooked through.",
      "Roast a tray of mixed vegetables alongside.",
      "Slice pork and portion into containers.",
    ],
  },
  {
    id: "rec-19",
    name: "Pulled Pork Sweet Potato Bowls",
    mealType: "Lunch",
    site: "recipecritic",
    youtubeQuery: "pulled pork sweet potato meal prep",
    perServing: { cal: 430, protein: 32, carbs: 40, fat: 14 },
    prepTimeMin: 15,
    cookTimeMin: 240,
    proteinTypes: ["pork"],
    searchKeywords: ["pork shoulder", "sweet potato"],
    steps: [
      "Slow-cook pork shoulder until tender, then shred.",
      "Roast sweet potato cubes.",
      "Combine with a light sauce; portion into containers.",
    ],
  },
  {
    id: "rec-20",
    name: "Turkey Meatballs with Zucchini Noodles",
    mealType: "Dinner",
    site: "skinnytaste",
    youtubeQuery: "turkey meatballs zucchini noodles meal prep",
    perServing: { cal: 360, protein: 34, carbs: 14, fat: 18 },
    prepTimeMin: 15,
    cookTimeMin: 20,
    proteinTypes: ["turkey"],
    searchKeywords: ["ground turkey", "zucchini noodles", "marinara"],
    steps: [
      "Mix and bake ground turkey meatballs.",
      "Spiralize zucchini into noodles.",
      "Toss noodles with marinara and meatballs; portion into containers.",
    ],
  },
  {
    id: "rec-21",
    name: "Garlic Butter Shrimp & Rice",
    mealType: "Lunch",
    site: "damndelicious",
    youtubeQuery: "garlic butter shrimp rice meal prep",
    perServing: { cal: 380, protein: 30, carbs: 38, fat: 12 },
    prepTimeMin: 10,
    cookTimeMin: 10,
    proteinTypes: ["fish"],
    searchKeywords: ["shrimp", "rice", "garlic butter"],
    steps: [
      "Saute shrimp in garlic butter until pink.",
      "Cook rice.",
      "Combine and portion into containers.",
    ],
  },
  {
    id: "rec-22",
    name: "Baked Cod with Vegetables",
    mealType: "Dinner",
    site: "feastingathome",
    youtubeQuery: "baked cod meal prep vegetables",
    perServing: { cal: 340, protein: 32, carbs: 20, fat: 12 },
    prepTimeMin: 10,
    cookTimeMin: 20,
    proteinTypes: ["fish"],
    searchKeywords: ["cod", "vegetables"],
    steps: [
      "Season cod fillets and arrange with a tray of mixed vegetables.",
      "Roast until the fish flakes easily.",
      "Portion into containers.",
    ],
  },
  {
    id: "rec-23",
    name: "Tuna Salad Lettuce Wraps",
    mealType: "Lunch",
    site: "eatingbirdfood",
    youtubeQuery: "tuna salad lettuce wraps meal prep",
    perServing: { cal: 280, protein: 28, carbs: 8, fat: 14 },
    prepTimeMin: 10,
    cookTimeMin: 0,
    proteinTypes: ["fish"],
    searchKeywords: ["tuna", "lettuce", "celery"],
    steps: [
      "Mix canned tuna with a light dressing and chopped vegetables.",
      "Spoon into lettuce leaves just before eating.",
      "Store tuna mixture and lettuce separately, portioned into containers.",
    ],
  },
  {
    id: "rec-24",
    name: "Breakfast Burrito Bowls",
    mealType: "Breakfast",
    site: "cleaneatingcouple",
    youtubeQuery: "breakfast burrito bowl meal prep",
    perServing: { cal: 350, protein: 22, carbs: 30, fat: 15 },
    prepTimeMin: 10,
    cookTimeMin: 15,
    proteinTypes: ["egg", "plantBased"],
    searchKeywords: ["eggs", "black beans", "avocado", "potatoes"],
    steps: [
      "Scramble eggs and warm black beans.",
      "Dice avocado and roast potatoes.",
      "Combine into bowls; portion into containers.",
    ],
  },
  {
    id: "rec-25",
    name: "Cottage Cheese Bowl with Fruit",
    mealType: "Snack",
    site: "eatingbirdfood",
    youtubeQuery: "cottage cheese bowl meal prep",
    perServing: { cal: 220, protein: 22, carbs: 20, fat: 5 },
    prepTimeMin: 5,
    cookTimeMin: 0,
    proteinTypes: ["dairy"],
    searchKeywords: ["cottage cheese", "fruit", "honey"],
    steps: [
      "Portion cottage cheese into containers.",
      "Top with fresh or frozen fruit and a drizzle of honey just before eating.",
    ],
  },
  {
    id: "rec-26",
    name: "Veggie Tofu Stir Fry",
    mealType: "Dinner",
    site: "minimalistbaker",
    youtubeQuery: "tofu vegetable stir fry meal prep",
    perServing: { cal: 360, protein: 20, carbs: 34, fat: 16 },
    prepTimeMin: 15,
    cookTimeMin: 15,
    proteinTypes: ["plantBased"],
    searchKeywords: ["tofu", "vegetables", "rice", "soy sauce"],
    steps: [
      "Press and pan-sear cubed tofu until golden.",
      "Stir-fry mixed vegetables.",
      "Combine with a soy-ginger sauce; serve over rice, portion into containers.",
    ],
  },
  {
    id: "rec-27",
    name: "Chickpea Salad Bowls",
    mealType: "Lunch",
    site: "cookieandkate",
    youtubeQuery: "chickpea salad meal prep bowls",
    perServing: { cal: 380, protein: 16, carbs: 46, fat: 14 },
    prepTimeMin: 15,
    cookTimeMin: 0,
    proteinTypes: ["plantBased"],
    searchKeywords: ["chickpeas", "vegetables", "tahini"],
    steps: [
      "Combine chickpeas, chopped vegetables, and a lemon-tahini dressing.",
      "Portion into containers.",
    ],
  },
  {
    id: "rec-28",
    name: "Lentil Soup",
    mealType: "Dinner",
    site: "feastingathome",
    youtubeQuery: "lentil soup meal prep",
    perServing: { cal: 320, protein: 18, carbs: 48, fat: 6 },
    prepTimeMin: 15,
    cookTimeMin: 35,
    proteinTypes: ["plantBased"],
    searchKeywords: ["lentils", "carrots", "celery", "broth"],
    steps: [
      "Saute onion, carrot, and celery.",
      "Add lentils, broth, and spices; simmer until tender.",
      "Portion into containers.",
    ],
  },
  {
    id: "rec-29",
    name: "Chicken Teriyaki Rice Bowls",
    mealType: "Lunch",
    site: "recipetineats",
    youtubeQuery: "chicken teriyaki meal prep bowls",
    perServing: { cal: 460, protein: 36, carbs: 52, fat: 11 },
    prepTimeMin: 10,
    cookTimeMin: 20,
    proteinTypes: ["chicken"],
    searchKeywords: ["chicken thigh", "rice", "teriyaki sauce", "broccoli"],
    steps: [
      "Sear sliced chicken thighs until cooked through.",
      "Add teriyaki sauce and simmer until glossy; steam broccoli.",
      "Serve over rice and portion into containers.",
    ],
  },
  {
    id: "rec-30",
    name: "Lemon Herb Chicken & Potatoes",
    mealType: "Dinner",
    site: "cafedelites",
    youtubeQuery: "lemon herb chicken potatoes sheet pan",
    perServing: { cal: 430, protein: 38, carbs: 32, fat: 16 },
    prepTimeMin: 15,
    cookTimeMin: 35,
    proteinTypes: ["chicken"],
    searchKeywords: ["chicken breast", "potatoes", "lemon", "herbs"],
    steps: [
      "Toss chicken and halved baby potatoes with lemon, garlic, herbs, and oil.",
      "Roast at 425°F until the potatoes are golden and the chicken reaches 165°F.",
      "Portion into containers.",
    ],
  },
  {
    id: "rec-31",
    name: "Chicken Burrito Bowls",
    mealType: "Lunch",
    site: "pinchofyum",
    youtubeQuery: "chicken burrito bowl meal prep",
    perServing: { cal: 480, protein: 38, carbs: 50, fat: 13 },
    prepTimeMin: 15,
    cookTimeMin: 20,
    proteinTypes: ["chicken"],
    searchKeywords: ["chicken breast", "rice", "black beans", "corn", "salsa"],
    steps: [
      "Season and cook chicken breast with chili powder and cumin; dice.",
      "Cook rice and warm black beans and corn.",
      "Assemble bowls with salsa and portion into containers.",
    ],
  },
  {
    id: "rec-32",
    name: "Thai Peanut Chicken Noodles",
    mealType: "Dinner",
    site: "pinchofyum",
    youtubeQuery: "thai peanut chicken noodles meal prep",
    perServing: { cal: 520, protein: 34, carbs: 55, fat: 18 },
    prepTimeMin: 15,
    cookTimeMin: 15,
    proteinTypes: ["chicken"],
    searchKeywords: ["chicken breast", "rice noodles", "peanut butter", "vegetables"],
    steps: [
      "Cook rice noodles and stir-fry sliced chicken with vegetables.",
      "Whisk peanut butter, soy sauce, lime, and a little honey into a sauce.",
      "Toss everything together and portion into containers.",
    ],
  },
  {
    id: "rec-33",
    name: "Chicken Tikka Masala with Rice",
    mealType: "Dinner",
    site: "recipetineats",
    youtubeQuery: "chicken tikka masala meal prep",
    perServing: { cal: 510, protein: 36, carbs: 50, fat: 17 },
    prepTimeMin: 15,
    cookTimeMin: 30,
    proteinTypes: ["chicken"],
    searchKeywords: ["chicken thigh", "tomato", "yogurt", "rice", "spices"],
    steps: [
      "Marinate chicken in yogurt and spices, then sear.",
      "Simmer in a spiced tomato sauce until thickened.",
      "Serve over rice and portion into containers.",
    ],
  },
  {
    id: "rec-34",
    name: "Chicken Pesto Pasta",
    mealType: "Lunch",
    site: "natashaskitchen",
    youtubeQuery: "chicken pesto pasta meal prep",
    perServing: { cal: 540, protein: 36, carbs: 55, fat: 19 },
    prepTimeMin: 10,
    cookTimeMin: 20,
    proteinTypes: ["chicken"],
    searchKeywords: ["chicken breast", "pasta", "pesto", "tomatoes"],
    steps: [
      "Cook pasta and pan-sear sliced chicken breast.",
      "Toss with pesto and halved cherry tomatoes.",
      "Portion into containers.",
    ],
  },
  {
    id: "rec-35",
    name: "Korean Beef Bowls",
    mealType: "Lunch",
    site: "damndelicious",
    youtubeQuery: "korean ground beef bowl meal prep",
    perServing: { cal: 470, protein: 30, carbs: 45, fat: 18 },
    prepTimeMin: 10,
    cookTimeMin: 15,
    proteinTypes: ["beef"],
    searchKeywords: ["ground beef", "rice", "soy sauce", "garlic", "ginger"],
    steps: [
      "Brown ground beef with garlic and ginger.",
      "Stir in soy sauce, a little brown sugar, and sesame oil.",
      "Serve over rice and portion into containers.",
    ],
  },
  {
    id: "rec-36",
    name: "Steak Fajita Bowls",
    mealType: "Dinner",
    site: "wellplated",
    youtubeQuery: "steak fajita bowl meal prep",
    perServing: { cal: 460, protein: 35, carbs: 38, fat: 18 },
    prepTimeMin: 15,
    cookTimeMin: 15,
    proteinTypes: ["beef"],
    searchKeywords: ["steak", "bell pepper", "onion", "rice"],
    steps: [
      "Sear seasoned flank or sirloin steak; rest and slice thin.",
      "Cook sliced peppers and onions in the same pan.",
      "Serve over rice and portion into containers.",
    ],
  },
  {
    id: "rec-37",
    name: "Beef Stroganoff with Egg Noodles",
    mealType: "Dinner",
    site: "natashaskitchen",
    youtubeQuery: "beef stroganoff meal prep",
    perServing: { cal: 530, protein: 32, carbs: 45, fat: 24 },
    prepTimeMin: 15,
    cookTimeMin: 25,
    proteinTypes: ["beef"],
    searchKeywords: ["beef", "mushrooms", "egg noodles", "sour cream"],
    steps: [
      "Sear strips of beef and set aside; cook mushrooms and onion.",
      "Make a quick sauce with broth and sour cream, then return the beef.",
      "Serve over egg noodles and portion into containers.",
    ],
  },
  {
    id: "rec-38",
    name: "Greek Beef Meatball Bowls",
    mealType: "Lunch",
    site: "wellplated",
    youtubeQuery: "greek meatball bowl meal prep",
    perServing: { cal: 490, protein: 32, carbs: 40, fat: 22 },
    prepTimeMin: 20,
    cookTimeMin: 20,
    proteinTypes: ["beef"],
    searchKeywords: ["ground beef", "rice", "cucumber", "tzatziki"],
    steps: [
      "Mix ground beef with garlic, oregano, and breadcrumbs; roll and bake meatballs.",
      "Cook rice and dice cucumber and tomato.",
      "Assemble bowls; pack tzatziki separately.",
    ],
  },
  {
    id: "rec-39",
    name: "Beef Shepherd's Pie",
    mealType: "Dinner",
    site: "simplyrecipes",
    youtubeQuery: "shepherds pie meal prep",
    perServing: { cal: 450, protein: 28, carbs: 35, fat: 21 },
    prepTimeMin: 20,
    cookTimeMin: 40,
    proteinTypes: ["beef"],
    searchKeywords: ["ground beef", "potatoes", "carrots", "peas"],
    steps: [
      "Brown ground beef with onion, carrots, and peas in a savory gravy.",
      "Top with mashed potatoes and bake until golden.",
      "Cool, cut into portions, and pack into containers.",
    ],
  },
  {
    id: "rec-40",
    name: "Pork Carnitas Rice Bowls",
    mealType: "Lunch",
    site: "simplyrecipes",
    youtubeQuery: "pork carnitas meal prep bowls",
    perServing: { cal: 500, protein: 34, carbs: 46, fat: 19 },
    prepTimeMin: 15,
    cookTimeMin: 180,
    proteinTypes: ["pork"],
    searchKeywords: ["pork shoulder", "rice", "black beans", "salsa"],
    steps: [
      "Braise pork shoulder with citrus and spices until tender, then shred and crisp.",
      "Cook rice and warm black beans.",
      "Assemble bowls with salsa and portion into containers.",
    ],
  },
  {
    id: "rec-41",
    name: "Honey Garlic Pork Chops & Green Beans",
    mealType: "Dinner",
    site: "cafedelites",
    youtubeQuery: "honey garlic pork chops meal prep",
    perServing: { cal: 420, protein: 36, carbs: 24, fat: 19 },
    prepTimeMin: 10,
    cookTimeMin: 20,
    proteinTypes: ["pork"],
    searchKeywords: ["pork chops", "green beans", "honey garlic sauce"],
    steps: [
      "Sear boneless pork chops until they reach 145°F.",
      "Glaze with honey garlic sauce; saute green beans alongside.",
      "Portion into containers.",
    ],
  },
  {
    id: "rec-42",
    name: "Pork Fried Rice",
    mealType: "Lunch",
    site: "recipetineats",
    youtubeQuery: "pork fried rice meal prep",
    perServing: { cal: 470, protein: 26, carbs: 55, fat: 16 },
    prepTimeMin: 10,
    cookTimeMin: 15,
    proteinTypes: ["pork", "egg"],
    searchKeywords: ["pork", "rice", "eggs", "peas", "carrots", "soy sauce"],
    steps: [
      "Stir-fry diced pork, then scramble eggs in the same pan.",
      "Add day-old rice, peas, carrots, and soy sauce; fry until hot.",
      "Portion into containers.",
    ],
  },
  {
    id: "rec-43",
    name: "Turkey Taco Lettuce Wraps",
    mealType: "Lunch",
    site: "skinnytaste",
    youtubeQuery: "turkey taco lettuce wraps",
    perServing: { cal: 320, protein: 30, carbs: 12, fat: 17 },
    prepTimeMin: 10,
    cookTimeMin: 15,
    proteinTypes: ["turkey"],
    searchKeywords: ["ground turkey", "lettuce", "taco seasoning", "salsa"],
    steps: [
      "Brown ground turkey with taco seasoning.",
      "Pack the turkey and salsa in containers.",
      "Keep lettuce leaves separate and wrap just before eating.",
    ],
  },
  {
    id: "rec-44",
    name: "Turkey & Sweet Potato Skillet",
    mealType: "Dinner",
    site: "eatingbirdfood",
    youtubeQuery: "ground turkey sweet potato skillet",
    perServing: { cal: 410, protein: 30, carbs: 35, fat: 16 },
    prepTimeMin: 10,
    cookTimeMin: 25,
    proteinTypes: ["turkey"],
    searchKeywords: ["ground turkey", "sweet potato", "spinach"],
    steps: [
      "Cook diced sweet potato in a skillet until tender.",
      "Add ground turkey and spices; cook through, then wilt in spinach.",
      "Portion into containers.",
    ],
  },
  {
    id: "rec-45",
    name: "Turkey Stuffed Peppers",
    mealType: "Dinner",
    site: "skinnytaste",
    youtubeQuery: "turkey stuffed peppers meal prep",
    perServing: { cal: 380, protein: 30, carbs: 30, fat: 14 },
    prepTimeMin: 15,
    cookTimeMin: 35,
    proteinTypes: ["turkey"],
    searchKeywords: ["ground turkey", "bell pepper", "rice", "tomato sauce"],
    steps: [
      "Mix browned ground turkey with cooked rice and tomato sauce.",
      "Stuff halved bell peppers and bake until tender.",
      "Portion into containers.",
    ],
  },
  {
    id: "rec-46",
    name: "Turkey Bolognese",
    mealType: "Dinner",
    site: "budgetbytes",
    youtubeQuery: "turkey bolognese meal prep",
    perServing: { cal: 490, protein: 33, carbs: 55, fat: 14 },
    prepTimeMin: 10,
    cookTimeMin: 30,
    proteinTypes: ["turkey"],
    searchKeywords: ["ground turkey", "pasta", "tomato sauce"],
    steps: [
      "Brown ground turkey with onion, carrot, and garlic.",
      "Simmer with crushed tomatoes until thick.",
      "Toss with cooked pasta and portion into containers.",
    ],
  },
  {
    id: "rec-47",
    name: "Salmon Rice Bowls",
    mealType: "Lunch",
    site: "eatingwell",
    youtubeQuery: "salmon rice bowl meal prep",
    perServing: { cal: 480, protein: 32, carbs: 42, fat: 20 },
    prepTimeMin: 10,
    cookTimeMin: 15,
    proteinTypes: ["fish"],
    searchKeywords: ["salmon", "rice", "cucumber", "edamame"],
    steps: [
      "Bake salmon fillets with soy sauce and a little honey.",
      "Cook rice; slice cucumber and thaw edamame.",
      "Flake salmon over rice and portion into containers.",
    ],
  },
  {
    id: "rec-48",
    name: "Cajun Shrimp & Sausage Skillet",
    mealType: "Dinner",
    site: "cafedelites",
    youtubeQuery: "cajun shrimp sausage skillet",
    perServing: { cal: 420, protein: 34, carbs: 20, fat: 22 },
    prepTimeMin: 10,
    cookTimeMin: 15,
    proteinTypes: ["fish", "pork"],
    searchKeywords: ["shrimp", "sausage", "bell pepper", "zucchini"],
    steps: [
      "Brown sliced smoked sausage.",
      "Add shrimp, peppers, zucchini, and Cajun seasoning; cook until the shrimp is pink.",
      "Portion into containers.",
    ],
  },
  {
    id: "rec-49",
    name: "Lemon Garlic Tilapia with Asparagus",
    mealType: "Dinner",
    site: "eatingwell",
    youtubeQuery: "lemon garlic tilapia asparagus",
    perServing: { cal: 380, protein: 34, carbs: 36, fat: 10 },
    prepTimeMin: 10,
    cookTimeMin: 15,
    proteinTypes: ["fish"],
    searchKeywords: ["tilapia", "rice", "asparagus", "lemon"],
    steps: [
      "Bake tilapia with lemon, garlic, and a little butter.",
      "Roast asparagus on the same tray; cook rice.",
      "Portion into containers.",
    ],
  },
  {
    id: "rec-50",
    name: "Tuna Pasta Salad",
    mealType: "Lunch",
    site: "budgetbytes",
    youtubeQuery: "tuna pasta salad meal prep",
    perServing: { cal: 430, protein: 28, carbs: 48, fat: 13 },
    prepTimeMin: 15,
    cookTimeMin: 10,
    proteinTypes: ["fish"],
    searchKeywords: ["tuna", "pasta", "celery", "peas"],
    steps: [
      "Cook and cool pasta.",
      "Mix with canned tuna, celery, peas, and a light yogurt-mayo dressing.",
      "Portion into containers and refrigerate.",
    ],
  },
  {
    id: "rec-51",
    name: "Shrimp Fried Rice",
    mealType: "Lunch",
    site: "damndelicious",
    youtubeQuery: "shrimp fried rice meal prep",
    perServing: { cal: 420, protein: 26, carbs: 52, fat: 11 },
    prepTimeMin: 10,
    cookTimeMin: 15,
    proteinTypes: ["fish", "egg"],
    searchKeywords: ["shrimp", "rice", "eggs", "peas", "carrots"],
    steps: [
      "Cook shrimp and set aside; scramble eggs.",
      "Fry day-old rice with peas, carrots, and soy sauce, then fold everything together.",
      "Portion into containers.",
    ],
  },
  {
    id: "rec-52",
    name: "Spinach & Feta Egg Bake",
    mealType: "Breakfast",
    site: "eatingwell",
    youtubeQuery: "spinach feta egg bake meal prep",
    perServing: { cal: 260, protein: 20, carbs: 8, fat: 16 },
    prepTimeMin: 10,
    cookTimeMin: 30,
    proteinTypes: ["egg", "dairy"],
    searchKeywords: ["eggs", "spinach", "feta"],
    steps: [
      "Whisk eggs with wilted spinach and crumbled feta.",
      "Bake in a greased dish until set.",
      "Cool, cut into squares, and pack into containers.",
    ],
  },
  {
    id: "rec-53",
    name: "Sausage & Egg Breakfast Burritos",
    mealType: "Breakfast",
    site: "budgetbytes",
    youtubeQuery: "freezer breakfast burritos",
    perServing: { cal: 420, protein: 24, carbs: 35, fat: 20 },
    prepTimeMin: 15,
    cookTimeMin: 15,
    proteinTypes: ["egg", "pork"],
    searchKeywords: ["eggs", "sausage", "tortillas", "cheese"],
    steps: [
      "Brown breakfast sausage and scramble eggs.",
      "Fill tortillas with sausage, eggs, and cheese; roll tightly.",
      "Wrap individually and refrigerate or freeze.",
    ],
  },
  {
    id: "rec-54",
    name: "Chickpea Curry with Rice",
    mealType: "Dinner",
    site: "loveandlemons",
    youtubeQuery: "chickpea curry meal prep",
    perServing: { cal: 450, protein: 15, carbs: 70, fat: 12 },
    prepTimeMin: 10,
    cookTimeMin: 25,
    proteinTypes: ["plantBased"],
    searchKeywords: ["chickpeas", "coconut milk", "tomatoes", "rice", "spices"],
    steps: [
      "Saute onion, garlic, ginger, and curry spices.",
      "Add chickpeas, tomatoes, and coconut milk; simmer until thick.",
      "Serve over rice and portion into containers.",
    ],
  },
  {
    id: "rec-55",
    name: "Lentil Bolognese",
    mealType: "Dinner",
    site: "minimalistbaker",
    youtubeQuery: "lentil bolognese",
    perServing: { cal: 430, protein: 22, carbs: 68, fat: 8 },
    prepTimeMin: 10,
    cookTimeMin: 30,
    proteinTypes: ["plantBased"],
    searchKeywords: ["lentils", "pasta", "tomato sauce"],
    steps: [
      "Saute onion, carrot, and garlic.",
      "Simmer with lentils and crushed tomatoes until the lentils are tender.",
      "Toss with pasta and portion into containers.",
    ],
  },
  {
    id: "rec-56",
    name: "Tofu Peanut Noodle Bowls",
    mealType: "Lunch",
    site: "pinchofyum",
    youtubeQuery: "tofu peanut noodles meal prep",
    perServing: { cal: 480, protein: 22, carbs: 55, fat: 19 },
    prepTimeMin: 15,
    cookTimeMin: 15,
    proteinTypes: ["plantBased"],
    searchKeywords: ["tofu", "rice noodles", "peanut butter", "vegetables"],
    steps: [
      "Press, cube, and bake or pan-fry tofu until crisp.",
      "Cook noodles and toss with vegetables and peanut sauce.",
      "Top with tofu and portion into containers.",
    ],
  },
  {
    id: "rec-57",
    name: "Black Bean Quinoa Burrito Bowls",
    mealType: "Lunch",
    site: "loveandlemons",
    youtubeQuery: "black bean quinoa burrito bowl",
    perServing: { cal: 440, protein: 17, carbs: 68, fat: 11 },
    prepTimeMin: 15,
    cookTimeMin: 20,
    proteinTypes: ["plantBased"],
    searchKeywords: ["black beans", "quinoa", "corn", "salsa", "avocado"],
    steps: [
      "Cook quinoa and warm seasoned black beans and corn.",
      "Assemble bowls with salsa.",
      "Add avocado just before eating so it doesn't brown.",
    ],
  },
  {
    id: "rec-58",
    name: "Greek Yogurt Chicken Salad",
    mealType: "Lunch",
    site: "eatingbirdfood",
    youtubeQuery: "greek yogurt chicken salad meal prep",
    perServing: { cal: 330, protein: 38, carbs: 14, fat: 13 },
    prepTimeMin: 15,
    cookTimeMin: 0,
    proteinTypes: ["chicken", "dairy"],
    searchKeywords: ["chicken breast", "greek yogurt", "celery", "grapes"],
    steps: [
      "Shred cooked chicken breast.",
      "Mix with Greek yogurt, diced celery, halved grapes, salt, and pepper.",
      "Portion into containers; serve with crackers or greens.",
    ],
  },
  {
    id: "rec-59",
    name: "Cottage Cheese Protein Pancakes",
    mealType: "Breakfast",
    site: "ifoodreal",
    youtubeQuery: "cottage cheese protein pancakes",
    perServing: { cal: 320, protein: 24, carbs: 35, fat: 9 },
    prepTimeMin: 10,
    cookTimeMin: 15,
    proteinTypes: ["dairy", "egg"],
    searchKeywords: ["cottage cheese", "oats", "eggs"],
    steps: [
      "Blend cottage cheese, oats, and eggs into a batter.",
      "Cook small pancakes on a nonstick pan.",
      "Cool and stack into containers; reheat in a toaster or microwave.",
    ],
  },
  {
    id: "rec-60",
    name: "Edamame & Hummus Snack Box",
    mealType: "Snack",
    site: "feastingathome",
    youtubeQuery: "healthy snack box meal prep",
    perServing: { cal: 260, protein: 14, carbs: 22, fat: 13 },
    prepTimeMin: 10,
    cookTimeMin: 0,
    proteinTypes: ["plantBased"],
    searchKeywords: ["edamame", "hummus", "cucumber", "carrots"],
    steps: [
      "Thaw shelled edamame.",
      "Pack hummus with cucumber and carrot sticks.",
      "Divide into snack containers.",
    ],
  },
];

RECOMMENDED_MEALS.forEach((m) => {
  m.sourceLabel = RECIPE_SITES[m.site].label;
  m.sourceUrl = siteSearchUrl(m.site, m.name);
});

const ACTIVITY_LEVELS = {
  sedentary: { label: "Sedentary (little/no exercise)", mult: 1.2 },
  light: { label: "Lightly active (1-3 days/wk)", mult: 1.375 },
  moderate: { label: "Moderately active (3-5 days/wk)", mult: 1.55 },
  active: { label: "Very active (6-7 days/wk)", mult: 1.725 },
  athlete: { label: "Athlete (2x/day training)", mult: 1.9 },
};

const RECIPE_CATEGORIES = ["Breakfast", "Lunch", "Dinner", "Snack", "Other"];

const UNIT_TO_GRAMS = { g: 1, kg: 1000, oz: 28.3495, lb: 453.592 };

// Protein-type taxonomy for the Meal Prep Planner's protein filter and the
// Recommended tab's search. "mine" recipes are classified by matching their
// ingredient names against this map; Recommended entries are tagged directly.
const PROTEIN_TYPES = {
  any: "Any protein",
  chicken: "Chicken",
  beef: "Beef",
  pork: "Pork",
  turkey: "Turkey",
  fish: "Fish & seafood",
  egg: "Egg",
  plantBased: "Plant-based (tofu, beans, lentils)",
  dairy: "Dairy (yogurt, cottage cheese)",
};

const FOOD_PROTEIN_TYPE = {
  "chicken breast, cooked": "chicken",
  "chicken thigh, cooked": "chicken",
  "ground beef 90/10, cooked": "beef",
  "ground turkey, cooked": "turkey",
  "pork tenderloin, cooked": "pork",
  "salmon, cooked": "fish",
  "tilapia, cooked": "fish",
  "shrimp, cooked": "fish",
  "cod, cooked": "fish",
  "tuna, canned in water": "fish",
  "egg, whole": "egg",
  "egg white": "egg",
  "tofu, firm": "plantBased",
  "black beans, cooked": "plantBased",
  "chickpeas, cooked": "plantBased",
  "lentils, cooked": "plantBased",
  "edamame": "plantBased",
  "greek yogurt, plain nonfat": "dairy",
  "cottage cheese, low fat": "dairy",
};

// Diet filters for the Meal Prep Planner. Thresholds are deliberately
// simplified (this app can't model diet phases or exact clinical protocols)
// but are grounded in how each diet is commonly and consistently described:
//  - Keto: ~70-75% of calories from fat, 20-25% protein, 5-10% carbs.
//  - Atkins: low-carb/higher-protein; historically phased (induction ~20g
//    net carbs/day up to a higher maintenance intake), which a per-recipe
//    filter can't represent, so this approximates the general approach.
//  - Low carb: a commonly used clinical threshold is roughly <=26% of
//    calories from carbohydrate.
//  - Volumetrics ("high volume, low calorie"): ranks/filters by energy
//    density (calories per gram) rather than a macro ratio, per Dr. Barbara
//    Rolls' Volumetrics research — low-density foods (produce, lean protein,
//    broth-based dishes) are roughly under ~1.5-2 kcal/g, vs. energy-dense
//    foods (oils, nuts, fried food) well above that.
//  - Carnivore: animal products only (meat, poultry, fish, eggs, dairy) with
//    no plant foods; checked ingredient-by-ingredient against the food
//    database below, so it only works for known ingredients.
const DIETS = {
  any: {
    label: "No specific diet",
    description: "No dietary restrictions — matches any recipe.",
  },
  keto: {
    label: "Keto (ketogenic)",
    description: "Very low carb, high fat: roughly 70-75% of calories from fat, 20-25% from protein, and 5-10% from carbs.",
    kind: "macroRatio",
    maxCarbPct: 10,
    minFatPct: 65,
  },
  atkins: {
    label: "Atkins-style (low carb)",
    description: "Low-carb, higher-protein eating in the style of the Atkins diet. This approximates the general approach — not the specific induction/maintenance phase targets — by keeping carbs low.",
    kind: "macroRatio",
    maxCarbPct: 15,
  },
  lowcarb: {
    label: "Low carb",
    description: "General low-carb eating: no more than about 26% of calories from carbohydrate, a commonly used low-carb threshold.",
    kind: "macroRatio",
    maxCarbPct: 26,
  },
  volumetrics: {
    label: "High volume, low calorie",
    description: "Favors lower energy-density recipes (more food weight per calorie, like vegetables, lean protein, and broth-based dishes) so portions feel larger for the same calories. Estimated as calories per gram across the whole recipe, so it only works for recipes with a real ingredient list (not the Recommended tab's placeholder entries).",
    kind: "density",
    maxKcalPerGram: 1.6,
  },
  carnivore: {
    label: "Carnivore",
    description: "Animal products only — meat, poultry, fish, eggs, and dairy — with no vegetables, fruit, grains, or legumes. Checked ingredient-by-ingredient against the built-in food database, so it only works for recipes built from known ingredients (not custom or placeholder ones).",
    kind: "ingredient",
  },
};

// Which FOOD_DB entries count as animal-derived, for the Carnivore diet filter.
const ANIMAL_FOOD_KEYS = new Set([
  "chicken breast, cooked",
  "chicken thigh, cooked",
  "ground beef 90/10, cooked",
  "ground turkey, cooked",
  "salmon, cooked",
  "tilapia, cooked",
  "shrimp, cooked",
  "egg, whole",
  "egg white",
  "greek yogurt, plain nonfat",
  "cottage cheese, low fat",
  "milk, 2%",
  "cheddar cheese",
  "mozzarella, part skim",
  "feta cheese",
  "butter",
]);

// Ingredients that are widely available pre-chopped or frozen at the
// grocery store, used to surface time-saving tips for a given recipe.
const FREEZABLE_OR_PRECUT_INGREDIENTS = new Set([
  "broccoli, cooked",
  "spinach, raw",
  "kale, raw",
  "bell pepper",
  "onion",
  "carrot",
  "zucchini",
  "mushroom",
  "edamame",
  "blueberries",
  "strawberries",
  "banana",
  "shrimp, cooked",
]);

const GENERIC_MEAL_PREP_TIPS = [
  "Cook proteins in one big batch, then portion once they've cooled — reheats better than cooking a whole tray fresh each day.",
  "Let food cool to room temperature before sealing containers; sealing while hot traps steam and makes everything soggy.",
  "Cook grains and starches slightly under, since they keep softening a bit as they reheat.",
  "Store sauces or dressings separately and add them at serving time so greens or grains don't get soggy in the fridge.",
  "Label containers with the date — most meal-prepped dishes keep 3-4 days refrigerated, or 2-3 months frozen.",
];
